workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

image: python:3.9

stages:
  - build
  - test

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

unittest:
  stage: test
  script:
    - pytest tests

mypy:
  stage: test
  script:
    - mypy src/

black:
  stage: test
  script:
    - black --diff --check src/

isort:
  stage: test
  script:
    - isort --check-only --diff src/

flake8:
  stage: test
  script:
    - flake8 src/
    
